import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const html = await readFile(resolve(root, "index.html"), "utf8");
const body = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i)?.[1];

if (!body) throw new Error("Could not find the landing-page body in index.html");

await writeFile(
  resolve(root, "app/landing.generated.ts"),
  `// Generated by scripts/prepare-site.mjs.\nexport const landingMarkup = ${JSON.stringify(body)};\n`,
);

await mkdir(resolve(root, "public"), { recursive: true });
for (const file of ["app.js", "config.js", "styles.css", "og.jpg"]) {
  await copyFile(resolve(root, file), resolve(root, "public", file));
}
